export const SET_USER_TIME_ZONES = "SET_USER_TIME_ZONES";
export const SET_OUTPUT_FORMATS = "SET_OUTPUT_FORMATS";
export const SET_SCHEDULER_UI_CONFIG = "SET_SCHEDULER_UI_CONFIG";
export const SET_SCHEDULE_APIS_FAILURE_ERROR =
  "SET_SCHEDULE_APIS_FAILURE_ERROR";
export const SET_REPOSITORY_FOLDER_DATA = "SET_REPOSITORY_FOLDER_DATA";
export const SET_PROPERTIES_DETAILS = "SET_PROPERTIES_DETAILS";
export const SET_FAKE_ROOT = "SET_FAKE_ROOT";
export const SET_VISITED_TABS = "SET_VISTED_TABS";
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";
export const SET_STEPPER_PROPERTIES = "SET_STEPPER_PROPERTIES";
export const SET_TABS_CONFIG = "SET_TABS_CONFIG";
export const SET_VISIBLE_FIELDS = "SET_VISIBLE_FIELDS";
export const SCHEDULE_ERROR_OCCURRED = "SCHEDULE_ERROR_OCCURRED";
export const SET_STEPPER_CONFIG = "SET_STEPPER_CONFIG";
// export const SET_USER_LOCALE = 'SET_USER_LOCALE';
