export const SET_USER_TIME_ZONES = "SET_USER_TIME_ZONES";
export const SET_OUTPUT_FORMATS = "SET_OUTPUT_FORMATS";
export const SET_SCHEDULER_UI_CONFIG = "SET_SCHEDULER_UI_CONFIG";
export const SET_REPOSITORY_FOLDER_DATA = "SET_REPOSITORY_FOLDER_DATA";
export const SET_PROPERTIES_DETAILS = "SET_PROPERTIES_DETAILS";
// export const SET_USER_LOCALE = 'SET_USER_LOCALE';
