name: Install and run Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn Install
        run: |
          yarn install

      - name: Build All
        run: |
          yarn workspaces run build

      - name: Test All
        run: |
          yarn workspaces run test

      - name: Clean All
        run: |
          yarn workspaces run clean
